language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_deploy: "./gradlew shadowJar"

deploy:
  provider: releases
  api_key:
    secure:
  file: "build/libs/SmartDashboard-all.jar"
  skip_cleanup: true
  on:
    repo: wpilibsuite/SmartDashboard
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
